apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: hubot-dc
labels:
  template: hubot-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    strategy:
      resources:
        requests:
          cpu: '100m'
        limits:
          cpu: '150m'
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}${SUFFIX}
      spec:
        containers:
        - image: ${NAME}:${VERSION}
          name: hubot
          ports:
          - containerPort: 8000
            protocol: TCP
          resources:
            requests:
              cpu: '100m'
            limits:
              cpu: '150m'
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 10
          env:
          - name: ROCKETCHAT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rocketchat-bot-account-password
                key: BOT_PASSWORD
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hubot-redis
                key: redis-password
          - name: ROCKETCHAT_URL
            value: ${ROCKETCHAT_URL_VALUE}
          - name: ROCKETCHAT_USER
            value: ${ROCKETCHAT_USER_VALUE}
          - name: ROCKETCHAT_USESSL
            value: ${ROCKETCHAT_USESSL_VALUE}
          - name: RESPOND_TO_DM
            value: ${RESPOND_TO_DM_VALUE}
          - name: ROCKETCHAT_ROOM
            value: ${ROCKETCHAT_ROOM_VALUE}
          - name: REDIS_URL
            value: redis://:$(REDIS_PASSWORD)@hubot-redis-master.${NAMESPACE}.svc.cluster.local
          - name: TZ
            value: America/Vancouver
          - name: HUBOT_LOG_LEVEL
            value: ${HUBOT_LOG_LEVEL_VALUE}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - hubot
        from:
          kind: ImageStreamTag
          namespace: ${NAMESPACE}
          name: ${NAME}:${VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    ports:
    - name: api
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    host:
    port:
      targetPort: api
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}${SUFFIX}
      weight: 100
    wildcardPolicy: None
parameters:
- description: Installation namespace
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: 6e2f55-test
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: hubot
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
- description: URL of rocketchat instance
  displayName: rocketchat url
  name: ROCKETCHAT_URL_VALUE
  required: true
- description: Username of the bot account in rocketchat
  displayName: bot username
  name: ROCKETCHAT_USER_VALUE
  required: true
- description: Should the bot connect to RocketChat using SSL?
  displayName: use ssl
  name: ROCKETCHAT_USESSL_VALUE
  required: true
- description: Can the bot respond to requests in DMs?
  displayName: dms allowed
  name: RESPOND_TO_DM_VALUE
  required: true
- description: Rooms in which the bot can respond
  displayName: bot rooms
  name: ROCKETCHAT_ROOM_VALUE
  required: false
- description: Log level
  displayName: log level
  name: HUBOT_LOG_LEVEL_VALUE
  value: warn
  required: true
