cluster:
  enabled: false
securityContext:
  enabled: false
containerSecurityContext:
  enabled: false
master:
  persistence:
    size: 1Gi
    accessModes: ['ReadWriteMany']
configmap: |-
  appendonly no
  save 60 1
image:
  pullSecrets: ['docker-pull-secret']
