---
- name: Sanity checks
  import_tasks: asserts.yml

- name: Vault root namespace tasks
  import_tasks: root-namespace.yml

- name: Vault platform-services namespace tasks
  import_tasks: platform-services-namespace.yml

