---
- name: Write Vault Policy to be used by Terraform
  hashivault_policy:
    name: "{{ item.name }}"
    rules_file: "{{ item.file }}"
    verify: "{{ vault_prepare_for_terraform_verify }}"
    namespace: "{{ vault_prepare_for_terraform_ns1 }}"
  loop:
  - { name: 'policyadmin', file: '{{ role_path}}/files/policyadmin_policy.hcl' }
  - { name: 'admin', file: '{{ role_path}}/files/admin_policy.hcl' }

- name: AppRole - Enable AppRole so Terraform can authenticate
  hashivault_auth_method:
    method_type: approle
    verify: "{{ vault_prepare_for_terraform_verify }}"
    namespace: "{{ vault_prepare_for_terraform_ns1 }}"

- name: AppRole - Configure an AppRole role attached to Vault policies
  hashivault_approle_role:
    name: "{{ vault_prepare_for_terraform_approle_role_name }}"
    secret_id_num_uses: "{{ vault_prepare_for_terraform_approle_sid_uses }}"
    token_policies: "{{ vault_prepare_for_terraform_approle_policies}} "
    token_ttl: "{{ vault_prepare_for_terraform_token_ttl }}"
    token_max_ttl: "{{ vault_prepare_for_terraform_token_max_ttl }}"
    verify: "{{ vault_prepare_for_terraform_verify }}"
    namespace: "{{ vault_prepare_for_terraform_ns1 }}"

- name: AppRole - Retrieve the Role ID from Vault
  hashivault_approle_role_id:
    name: "{{ vault_prepare_for_terraform_approle_role_name }}"
    verify: "{{ vault_prepare_for_terraform_verify }}"
    namespace: "{{ vault_prepare_for_terraform_ns1 }}"
  register: r_vault_approle_role_id

- name: AppRole - Role ID
  debug: msg="Vault platform-services namespace - AppRole Role ID is {{ r_vault_approle_role_id.id }}"

