---
- name: Create Vault Namespace platform-services
  hashivault_namespace:
    name: platform-services
    verify: "{{ vault_prepare_for_terraform_verify }}"

- name: Write Vault Policy to be used by Terraform
  hashivault_policy:
    name: "{{ item.name }}"
    rules_file: "{{ item.file }}"
    verify: "{{ vault_prepare_for_terraform_verify }}"
  loop:
  - { name: 'policyadmin', file: '../roles/vault_prepare_for_terraform/files/policyadmin_policy.hcl' }
  - { name: 'namespaceadmin', file: '../roles/vault_prepare_for_terraform/files/root_ns_admin_policy.hcl' }
  # {{ role_path }}

- name: AppRole - Enable AppRole so Terraform can authenticate
  hashivault_auth_method:
    method_type: approle
    verify: "{{ vault_prepare_for_terraform_verify }}"

- name: AppRole - Configure an AppRole role attached to Vault policies
  hashivault_approle_role:
    name: "{{ vault_prepare_for_terraform_approle_role_name }}"
    secret_id_num_uses: "{{ vault_prepare_for_terraform_approle_sid_uses }}"
    token_policies: "{{ vault_prepare_for_terraform_approle_policies}} "
    token_ttl: "{{ vault_prepare_for_terraform_token_ttl }}"
    token_max_ttl: "{{ vault_prepare_for_terraform_token_max_ttl }}"
    verify: "{{ vault_prepare_for_terraform_verify }}"

- name: AppRole - Retrieve the Role ID from Vault
  hashivault_approle_role_id:
    name: "{{ vault_prepare_for_terraform_approle_role_name }}"
    verify: "{{ vault_prepare_for_terraform_verify }}"
  register: r_vault_approle_role_id

- name: AppRole - Role ID
  debug: msg="Vault root namespace - AppRole Role ID is {{ r_vault_approle_role_id.id }}"

