---
- hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks: 
  
    - include_tasks: tasks/loop_tests.yml
      with_items: 
        - "{{ test_patterns }}"
    - debug: msg="{{ report_records }}"

    - name: Create CSV output
      template: 
        src: templates/report_output.csv.j2
        dest: "report.csv"


