
# Moved to platform ops repository to better track all cluster role creation.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: artifactory-operator
  namespace: devops-artifactory
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - routes
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - artifactory-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - artifactoryrepo.operators.bcgov
  resources:
  - '*'
  verbs:
  - '*'
