apiVersion: v1
data:
  hooks.yml: |-
    - id: webhook
      execute-command: /opt/run-playbook.sh
      command-working-directory: /opt
      response-message: I got the payload!
      pass-arguments-to-command:
      - source: payload
        name: pull_request.head.repo.html_url
      - source: payload
        name: pull_request.head.ref
      - source: payload
        name: number
      - source: payload
        name: pull_request.head.repo.owner.login
      - source: payload
        name: pull_request.url
      trigger-rule:
        and:
        - match:
            type: payload-hash-sha1
            secret: mysecret
            parameter:
              source: header
              name: X-Hub-Signature
        - match:
            type: value
            value: opened
            parameter:
              source: payload
              name: action
kind: ConfigMap
metadata:
  name: webhook-ansible-hooks
