---
- hosts: localhost
  connection: local
  vars_files:
    creds/vars.yml
  tasks: 
    # - name: Clone Repo
    #   git: 
    #     repo: "{{ repo_url }}"
    #     dest: git_checkout
    # - name: clean up git checkout
    #   command: rm -rf git_checkout/.git 
    - name: Get list of PR files
      uri: 
        method: GET
        url: "{{ pull_request_url }}/files"
        headers: 
          Authorization: "Bearer {{ gh_token }}"
        return_content: true
      register: pr_files
    - name: debug
      debug: msg="{{ pr_files }}"
    - name: Add comment before closing
      uri: 
        method: POST
        url: "{{ pr_comments_url }}"
        headers: 
          Authorization: "Bearer {{ gh_token }}"
        body: '{ "body": "realm-o-matic auto-close"}'
        status_code: 201
    - name: Merge Pull Request
      uri: 
        method: PUT
        url: "{{ pull_request_url }}/merge"
        headers: 
          Authorization: "Bearer {{ gh_token }}"
    - name: Close Pull Request
      uri: 
        method: PATCH
        url: "{{ pull_request_url }}"
        headers: 
          Authorization: "Bearer {{ gh_token }}"
        body: '{"state":"closed"}'
    # - name: Cleanup
    #   file: 
    #     state: absent
    #     path: git_checkout
