apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      template: hubot-template
    name: nodejs-10
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: 10
        namespace: openshift
      importPolicy: {}
      name: nodejs
      referencePolicy:
        type: Source
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      template: hubot-template
    name: hubot
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      template: hubot-template
    name: hubot-dev
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: hubot:v1.0.0
    postCommit: {}
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 1
        memory: 2Gi
    source:
      contextDir: ""
      git:
        ref: master
        uri: https://github.com/caggles/hubot-test
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs-10:10.15.0-1
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
kind: List
metadata: {}
