format_version: 3
pipelines:
  test:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/BCDevOps/platform-services
        shallow_clone: true
        auto_update: true
        branch: status-page
    stages:
    - uninstall-dev:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          cleanDev:
            # elastic_profile_id: standard-agent
            timeout: 0
            tasks:            
            - exec:
                command: /bin/bash
                arguments: 
                  - -c 
                  - apps/statuspage/.gocd/uninstall.sh
                run_if: passed
          deployDev:
            # elastic_profile_id: standard-agent
            timeout: 0
            tasks:            
            - exec:
                command: /bin/bash
                arguments: 
                  - -c 
                  - apps/statuspage/.gocd/install.sh
                run_if: passed
            # - exec:
            #     arguments:
            #     - -i 
            #     - prod 
            #     - statuspage.yml  
            #     - -e
            #     - activity=uninstall 
            #     - -e 
            #     - env=prod
            #     command: ansible-playbook
            #     run_if: passed
            #     working_directory: apps/statuspage/ansible