apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-security-vault-pv-claim
  namespace: devops-security-vault
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
# storageClassName gp2 is specific to AWS Cloud
