---
# Set some defaults to assume the standard namespaces provigioned 
# for each team
- name: Set prefix
  set_fact: 
    ns_prefix: "{{ ansible_operator_meta.namespace.split('-tools')[0] | lower }}"
- name: Create additional variables
  set_fact: 
    namespaces: ["{{ ns_prefix}}-tools", "{{ ns_prefix}}-dev","{{ ns_prefix }}-test", "{{ ns_prefix }}-prod"]
    container_team_name:  "{{ ns_prefix }}-team"
    host_team_name: "{{ ns_prefix }}-team-persistent-storage"
    container_team_exists: false
    host_team_exists: false