apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networksecuritypolicies.secops.pathfinder.gov.bc.ca
spec:
  group: secops.pathfinder.gov.bc.ca
  names:
    kind: NetworkSecurityPolicy
    listKind: SecOpsPolicyList
    plural: networksecuritypolicies
    singular: networksecuritypolicy
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
