---
- name: Sanity check - Helm installed?
  command: which helm
  changed_when: false
  failed_when: r_helm_installed.rc not in [0]
  register: r_helm_installed

- name: Helm - add HashiCorp repository
  command: helm repo add hashicorp "{{ vault_install_helm_repo_url }}"

- name: Create working directory
  file:
    path: "{{ vault_install_working_dir }}"
    state: directory

- name: Generate Helm values file in working directory
  template:
    src: "{{ vault_install_chart_value_template }}"
    dest: "{{ vault_install_working_dir }}/{{ vault_install_chart_value_file }}"

- name: Helm - template out chart to multiple files
  shell: >
    helm template --dry-run vault hashicorp/vault --namespace "{{ vault_install_ocp_namespace }}"
    --set='server.image.repository=hashicorp/vault-enterprise'
    --set='server.image.tag=1.4.2_ent'
    --set='server.ha.enabled=true'
    --set='server.ha.raft.enabled=true'
    --set='global.tlsDisable=false'
    --set='global.openshift=true'
    --values "{{ vault_install_working_dir }}/{{ vault_install_chart_value_file }}"
    | awk -vout="{{ vault_install_working_dir }}" -F": " '$0~/^# Source: /{file=out"/"$2; print "Creating "file; system ("mkdir -p $(dirname "file"); echo -n "" > "file)} $0!~/^#/ && $0!="---"{print $0 >> file}'
    
- name: Bug fix - fix ^M line endings in OpenShift Route object
  shell: sed -i'' 's/\r$//g' "{{ vault_install_working_dir }}/vault/templates/server-route.yaml"

- name: Bug fix - fix missing namespace in OpenShift Route object
  lineinfile:
    path: "{{ vault_install_working_dir }}/vault/templates/server-route.yaml"
    insertafter: '^  name: vault'
    line: '  namespace: {{ vault_install_ocp_namespace }}'

- name: Install Vault on OCP cluster
  k8s:
    namespace: "{{ vault_install_ocp_namespace }}"
    src: "{{ item }}"
    state: present
  with_fileglob:
    - "{{ vault_install_working_dir }}/vault/templates/*.yaml"
  tags: build

