apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysdig-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sysdig-monitor
  template:
    metadata:
      labels:
        name: sysdig-monitor
    spec:
      serviceAccountName: sysdig-monitor
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: quay.io/shea_stewart/sysdig-monitor:latest
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: quay.io/shea_stewart/sysdig-monitor:latest
          imagePullPolicy: "Always"
          command:
            - /usr/local/bin/entrypoint
            - '--max-workers=5'
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              value: ''
            - name: SYSDIG_TOKEN
              value: ''
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sysdig-monitor"
      volumes:
        - name: runner
          emptyDir: {}
