kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sysdig-monitor
subjects:
- kind: ServiceAccount
  name: sysdig-monitor
  namespace: devops-sysdig # change this!
roleRef:
  kind: ClusterRole
  name: sysdig-monitor
  apiGroup: rbac.authorization.k8s.io
