## Allow project admins/editors to manage networksecuritypolicy objects
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: aggregate-monitoring-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true" 
rules:
- apiGroups: ["ops.gov.bc.ca"] 
  resources: ["sysdig-teams"] 
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"] 