apiVersion: v1
kind: Template
metadata:
  name: ${ARTIFACTORY_NAME}-storage
  annotations:
    description: "Template to create Artifactory HA storage"
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: ${ARTIFACTORY_NAME}-pv
    name: ${ARTIFACTORY_NAME}-artifactory-ha-data-pvc-0
  spec:
    storageClassName: gluster-file-db
    accessModes: 
      - ReadWriteMany
    resources:
      requests:
        storage: ${ARTIFACTORY_DATA_PVC_SIZE}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: ${ARTIFACTORY_NAME}-pv
    name: ${ARTIFACTORY_NAME}-artifactory-ha-backup-pvc
  spec:
    storageClassName: gluster-file-db
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: ${ARTIFACTORY_BACKUP_PVC_SIZE}
#- apiVersion: v1
#  kind: PersistentVolumeClaim
#  metadata:
#    labels:
#      app: ${ARTIFACTORY_NAME}-pv
#    name: volume-${ARTIFACTORY_NAME}-artifactory-ha-primary-0
#  spec:
#    storageClassName: gluster-file
#    accessModes:
#      - ReadWriteOnce
#    resources:
#      requests:
#        storage: ${ARTIFACTORY_SS_SIZE}
#- apiVersion: v1
#  kind: PersistentVolumeClaim
#  metadata:
#    labels:
#      app: ${ARTIFACTORY_NAME}-pv
#    name: volume-${ARTIFACTORY_NAME}-artifactory-ha-member-0
#  spec:
#    storageClassName: gluster-file
#    accessModes:
#      - ReadWriteOnce
#    resources:
#      requests:
#        storage: ${ARTIFACTORY_SS_SIZE}

parameters:
- description: Artifactory name
  name: ARTIFACTORY_NAME
  value: "artifactory"
  required: true
- description: Artifactory file storage data size
  name: ARTIFACTORY_DATA_PVC_SIZE
  default: 100Gi
- description: Artifactory backup PVC size
  name: ARTIFACTORY_BACKUP_PVC_SIZE
  default: 50Gi
- description: Artifactory statefulSet storage size
  name: ARTIFACTORY_SS_SIZE
  default: 5Gi
