apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |-
      Patroni Postgresql database cluster, with persistent storage.
    iconClass: icon-postgresql
    openshift.io/display-name: Patroni Postgresql (Persistent)
    openshift.io/long-description: This template deploys a patroni postgresql HA
      cluster with persistent storage.
    tags: postgresql
  name: patroni-pgsql-persistent
labels:
  app.kubernetes.io/component: database
  app.kubernetes.io/name: patroni
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/version: "10"
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: ${DATABASE_NAME}${SUFFIX}
      cluster-name: ${DATABASE_NAME}${SUFFIX}
    annotations:
      as-copy-of: "template.${DATABASE_NAME}-patroni"
    name: ${DATABASE_NAME}${SUFFIX}
  stringData:
    replication-username: ${PATRONI_REPLICATION_USERNAME}
    replication-password: ${PATRONI_REPLICATION_PASSWORD}
    superuser-username: ${PATRONI_SUPERUSER_USERNAME}
    superuser-password: ${PATRONI_SUPERUSER_PASSWORD}
    app-db-name: ${APP_DB_NAME}
    app-db-username: ${APP_DB_USERNAME}
    app-db-password: ${APP_DB_PASSWORD}
parameters:
- description: The name of the application for labelling all artifacts.
  displayName: Application Name
  name: DATABASE_NAME
  value: patroni
- name: SUFFIX
- description: Username of the superuser account for initialization.
  displayName: Superuser Username
  name: PATRONI_SUPERUSER_USERNAME
  value: postgres
  generate: expression
  from: super-[a-zA-Z0-9]{6}
- description: Password of the superuser account for initialization.
  displayName: Superuser Password
  name: PATRONI_SUPERUSER_PASSWORD
  generate: expression
  from: '[a-zA-Z0-9]{32}'
- description: Username of the replication account for initialization.
  displayName: Replication Username
  name: PATRONI_REPLICATION_USERNAME
  value: replication
  generate: expression
  from: rep-[a-zA-Z0-9]{6}
- description: Password of the replication account for initialization.
  displayName: Replication Password
  name: PATRONI_REPLICATION_PASSWORD
  generate: expression
  from: '[a-zA-Z0-9]{32}'
- name: APP_DB_USERNAME
  value: app
- name: APP_DB_NAME
  value: app
- name: APP_DB_PASSWORD
  generate: expression
  from: '[a-zA-Z0-9]{32}'
- description: Artifactory name
  name: ARTIFACTORY_NAME
  value: "artifactory-ha"
  required: true
