--- 
- name: "{{ activity }} {{ item }}  in {{ env }}" 
  include_tasks: manage_statefulsets.yml
  with_items: 
    - prometheus
- name: "{{ activity }} {{ item }}  in {{ env }}" 
  include_tasks: manage_deployments.yml
  with_items: 
    - blackbox-exporter
    - grafana
    - envoy





            # stage ('Deploy Dev'){
            #     parallel (
            #         'Prometheus': {
            #             stage ('Deploy Prometheys') {
            #                 dir ("apps/statuspage/manifests") {
            #                     sh "ls -lha"
            #                     sh """oc apply -f service-prometheus.yml -n ${DEV_NAMESPACE}"""
            #                     sh """oc apply -f configmap-prometheus.yml -n ${DEV_NAMESPACE}"""
            #                     sh """oc apply -f route-prometheus.yml -n ${DEV_NAMESPACE}"""
            #                     sh """cat statefulset-prometheus.yml | sed 's/{{ VERSION }}/${PROMETHEUS_VERSION}/g'| oc apply -f - -n ${DEV_NAMESPACE}"""
            #                 }
            #             }
            #         },
            #         'Blackbox': {
            #             stage('Deploy Blackbox'){
            #                 dir ("apps/statuspage/manifests") {                            
            #                     sh """oc apply -f service-blackbox-exporter.yml -n ${DEV_NAMESPACE}"""
            #                     sh """oc apply -f configmap-blackbox-exporter.yml -n ${DEV_NAMESPACE}"""
            #                     sh """cat deployment-blackbox-exporter.yml | sed 's/{{ VERSION }}/${BLACKBOX_VERSION}/g'| oc apply -f - -n ${DEV_NAMESPACE}"""
            #                 }
            #             }
            #         },
            #         'Grafana': {
            #             stage('Deploy Grafana'){
            #                 dir ("apps/statuspage/manifests") {
            #                     sh """oc apply -f service-grafana.yml -n ${DEV_NAMESPACE}"""
            #                     sh """oc apply -f route-grafana.yml -n ${DEV_NAMESPACE}"""
            #                     sh """oc apply -f pvc-grafana.yml -n ${DEV_NAMESPACE}"""
            #                     sh """cat deployment-grafana.yml | sed 's/{{ VERSION }}/${GRAFANA_VERSION}/g'| oc apply -f - -n ${DEV_NAMESPACE}"""
            #                 }
            #             }
            #         },
            #         'Envoy': {
            #             stage('Deploy Envoy'){
            #                 dir ("apps/statuspage/manifests") {
            #                     sh """oc apply -f service-envoy.yml -n ${DEV_NAMESPACE}"""
            #                     sh """oc apply -f route-envoy.yml -n ${DEV_NAMESPACE}"""
            #                     sh """oc apply -f configmap-envoy.yml -n ${DEV_NAMESPACE}"""
            #                     sh """cat deployment-envoy.yml | sed 's/{{ VERSION }}/${ENVOY_VERSION}/g'| oc apply -f - -n ${DEV_NAMESPACE}"""
            #                 }
            #             }
            #         },
            #     )
                
            # }