--- 
- name: Create deployment file
  template:
    src: manifests/templates/template-{{ item }}.yml.j2
    dest: manifests/template-{{ item }}.yml
  with_items: 
    - "{{ patroni_cluster_name }}"
    - "{{ grafana_service_name }}"
    - "{{ prometheus_service_name }}"
    - "{{ envoy_service_name }}"
    - "{{ blackbox_service_name }}"
- name: Create objects
  command: "oc apply -f manifests/template-{{ item }}.yml -n {{ namespace }}"
  with_items: 
    - "{{ patroni_cluster_name }}"
    - "{{ grafana_service_name }}"
    - "{{ prometheus_service_name }}"
    - "{{ envoy_service_name }}"
    - "{{ blackbox_service_name }}"
  when: activity == "install"
- name: Delete objects
  command: "oc delete -f manifests/template-{{ item }}.yml -n {{ namespace }}"
  with_items: 
    - "{{ patroni_cluster_name }}"
    - "{{ grafana_service_name }}"
    - "{{ prometheus_service_name }}"
    - "{{ envoy_service_name }}"
    - "{{ blackbox_service_name }}"
  when: activity == "uninstall"
  ignore_errors: true
- name: Delete patroni configmaps
  command: "oc delete configmap -l app={{ patroni_cluster_name }} -n {{ namespace }}"
  when: activity == "uninstall"