--- 
- name: Create deployment file
  template:
    src: manifests/templates/template-{{ item }}.yml.j2
    dest: manifests/template-{{ item }}.yml
  with_items: 
    - "{{ grafana_service_name }}"
    - "{{ prometheus_service_name }}"
    - "{{ envoy_service_name }}"
    - "{{ blackbox_service_name }}"
# - name: Apply Templates
#   k8s: 
#     state: "{{ state }}"
#     namespace: "{{ namespace }}"
#     definition: "{{ lookup('file', 'manifests/template-{{ item }}.yml') }}"
#     wait: yes
#     wait_timeout: 180
#   with_items: 
#     - "{{ grafana_service_name }}"
#     - "{{ prometheus_service_name }}"
#     - "{{ envoy_service_name }}"
#     - "{{ blackbox_service_name }}"
- name: Create objects
  command: "oc apply -f manifests/template-{{ item }}.yml -n {{ namespace }}"
  with_items: 
    - "{{ grafana_service_name }}"
    - "{{ prometheus_service_name }}"
    - "{{ envoy_service_name }}"
    - "{{ blackbox_service_name }}"
  when: activity == "install"
- name: Delete objects
  command: "oc delete all -l app={{ item }} -n {{ namespace }}"
  with_items: 
    - "{{ grafana_service_name }}"
    - "{{ prometheus_service_name }}"
    - "{{ envoy_service_name }}"
    - "{{ blackbox_service_name }}"
  when: activity == "uninstall"