---
- hosts: localhost
  connection: local
  become: false
  vars_files: 
    - vars.yml
  tasks: 
    - name: Create deployment file
      template:
        src: manifests/templates/template-{{ item }}.yml.j2
        dest: manifests/template-{{ item }}.yml
      with_items: 
        - "{{ patroni_cluster_name }}"

    - name: Create objects
      command: "oc apply -f manifests/template-{{ item }}.yml -n {{ namespace }}"
      with_items: 
        - "{{ patroni_cluster_name }}"

      when: activity == "install"
    - name: Delete objects
      command: "oc delete all -l app={{ item }} -n {{ namespace }}"
      with_items: 
        - "{{ patroni_cluster_name }}"

      when: activity == "uninstall"