apiVersion: v1
data:
  prometheus.yml: |-
    # my global config
    global:
      scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).

    scrape_configs:
      - job_name: 'blackbox_tls_verify'
        metrics_path: /probe
        params:
          module: [http_2xx]  # Look for a HTTP 200 response.
        static_configs:
          - targets:
            - https://github.com/bcdevops/platform-services 
            - https://access.redhat.com/containers/
            - https://console.pathfinder.gov.bc.ca
            - https://failme.pathfinder.gov.bc.ca
            - https://hawkular-metrics.pathfinder.gov.bc.ca
            - http://labs-devops-platform-workshops.lab.pathfinder.gov.bc.ca 
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
      - job_name: 'blackbox_no_tls_verify'
        metrics_path: /probe
        params:
          module: [http_2xx__no_tls_verify]  # Look for a HTTP 200 response.
        static_configs:
          - targets:
            - https://kubernetes.default.svc.cluster.local
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.        
            
kind: ConfigMap
metadata:
  name: prometheus