apiVersion: v1
data:
  config.yml: |-
    modules:
      http_2xx:
        prober: http
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          valid_status_codes: []  # Defaults to 2xx
          method: GET
          preferred_ip_protocol: "ip4" # defaults to "ip6"
          ip_protocol_fallback: false  # no fallback to "ip6"
      http_2xx__no_tls_verify:
        prober: http
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          valid_status_codes: []  # Defaults to 2xx
          method: GET
          preferred_ip_protocol: "ip4" # defaults to "ip6"
          ip_protocol_fallback: false  # no fallback to "ip6"
          tls_config:
            insecure_skip_verify: true
      http_post_2xx:
        prober: http
        http:
          method: POST
      tcp_connect:
        prober: tcp
      pop3s_banner:
        prober: tcp
        tcp:
          query_response:
          - expect: "^+OK"
          tls: true
          tls_config:
            insecure_skip_verify: true
kind: ConfigMap
metadata:
  name: blackbox-exporter
