---
# Vault AppRole Role name used by Terraform
vault_prepare_for_terraform_approle_role_name: "terraform"

# Vault policies attached to the AppRole used by Terraform
vault_prepare_for_terraform_approle_policies: "default,policyadmin,namespaceadmin"

# Vault AppRole SecretID number of uses (0 means infinite)
vault_prepare_for_terraform_approle_sid_uses: "3"

# Vault Token TTL for the AppRole issued Vault Token
vault_prepare_for_terraform_token_ttl: "5m" # 5m

# Vault Token MaxTTL for the AppRole issued Vault Token
vault_prepare_for_terraform_token_max_ttl: "10m" # 10m

# Certificate verification toggle
vault_prepare_for_terraform_verify: False

# Vault Namespace to create
vault_prepare_for_terraform_ns1: "platform-services"

# vault_prepare_for_terraform_

