kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: artifactory-sa-operator
  namespace: devops-artifactory
subjects:
- kind: ServiceAccount
  name: artifactory-sa-operator
roleRef:
  kind: Role
  name: artifactory-sa-operator
  apiGroup: rbac.authorization.k8s.io
