---
- name: Get project data
  set_fact:
    project_details: "{{ lookup('k8s', api_version='v1', kind='Project', resource_name=item.metadata.namespace ) }}"
- debug: 
    msg: "{{ project_details }}"
### Stuck here needing to define a value if the dict object doesn't exist
- name: set undefined variables
  set_fact: 
    product_lead: "no-data"
  when: project_details|selectattr("metadata.annotations.product-lead", "defined")|list|length >0
- name: Send some output
  debug: 
    msg: "Project {{ item.metadata.namespace }} has BuildConfig {{ item.metadata.name }} with Git Org {{ item.spec.source.git.uri.split('/')[3] }} and repository {{ item.spec.source.git.uri.split('/')[4] }} and {{ product_lead }}"
  when: 
    - item.spec.source.type == "Git"
    - item.spec.source.git.uri.find('BCDevOps') != -1 or item.spec.source.git.uri.find('bcgov-c') != -1