---
- name: "Delete NetworkSecurityPolicy - {{ ansible_operator_meta.name }}"
  command: |
    apoctl api delete \
    networkaccesspolicies {{ policy_name }} \
    --namespace {{ aporeto_namespace }}
