---
  # tasks file for NetworkSecurityPolicy Create / Update
  - name: Debug metadata
    debug: 
      var: ansible_operator_meta
      verbosity: 3
  
  - name: Debug description
    debug: 
      var: description
      verbosity: 3

  - name: Debug source
    debug: 
      var: source
      verbosity: 3

  - name: Debug destination
    debug: 
      var: destination
      verbosity: 3

  - name: Set vars for custom-netpol template generation
    set_fact:
      aporeto_base_namespace: "{{ lookup('env', 'APORETO_BASE_NAMESPACE') }}"
      import_label: "{{ ansible_operator_meta.namespace }}-{{ ansible_operator_meta.name }}"
      policy_name: "custom-netpol-{{ ansible_operator_meta.name }}"
  
  - name: Set aporeto_namespace
    set_fact:
      aporeto_namespace: "{{ aporeto_base_namespace }}/{{ ansible_operator_meta.namespace }}"
  
  - name: Debug Aporeto Namespaces
    debug:
      msg:
        - "aporeto_base_namespace: {{ aporeto_base_namespace }}"
        - "aporeto_namespace: {{ aporeto_namespace }}"
        - "import_label: {{ import_label }}"
        - "policy_name: {{ policy_name }}"
      verbosity: 1
  
  - name: Create Or Update Policy
    command: |
      apoctl api import \
      --namespace {{ aporeto_namespace }} \
      -f -
    args:
      stdin: "{{ lookup('template', 'custom-netpol.yaml.j2') }}"