apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: sysdig-agent-tmpl
objects:
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    labels:
      app: sysdig-agent
      app_group: sysdig-agent-${REGION}
    name: sysdig-agent-${REGION}
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app_group: sysdig-agent-${REGION}
    template:
      metadata:
        labels:
          app: sysdig-agent
          app_group: sysdig-agent-${REGION}
      spec:
        containers:
        - image: sysdig/agent
          imagePullPolicy: Always
          name: sysdig-agent
          readinessProbe:
            exec:
              command:
              - test
              - -e
              - /opt/draios/logs/running
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command:
              - test
              - -e
              - /opt/draios/logs/running
            failureThreshold: 6
            initialDelaySeconds: 600
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${LIMIT_CPU}
              memory: ${LIMIT_MEM}
            requests:
              cpu: ${REQUEST_CPU}
              memory: ${REQUEST_MEM}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /host/var/run/docker.sock
            name: docker-sock
          - mountPath: /host/dev
            name: dev-vol
          - mountPath: /host/proc
            name: proc-vol
            readOnly: true
          - mountPath: /host/boot
            name: boot-vol
            readOnly: true
          - mountPath: /host/lib/modules
            name: modules-vol
            readOnly: true
          - mountPath: /host/usr
            name: usr-vol
            readOnly: true
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /opt/draios/etc/kubernetes/config
            name: sysdig-agent-config
          - mountPath: /opt/draios/etc/kubernetes/secrets
            name: sysdig-agent-secrets
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        hostPID: true
        nodeSelector:
          region: "${REGION}"
          sysdig-agent: "true"
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: sysdig-agent
        serviceAccountName: sysdig-agent
        terminationGracePeriodSeconds: 5
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        volumes:
        - emptyDir:
            medium: Memory
          name: dshm
        - hostPath:
            path: /var/run/docker.sock
            type: ""
          name: docker-sock
        - hostPath:
            path: /dev
            type: ""
          name: dev-vol
        - hostPath:
            path: /proc
            type: ""
          name: proc-vol
        - hostPath:
            path: /boot
            type: ""
          name: boot-vol
        - hostPath:
            path: /lib/modules
            type: ""
          name: modules-vol
        - hostPath:
            path: /usr
            type: ""
          name: usr-vol
        - configMap:
            defaultMode: 420
            name: sysdig-agent-${REGION}
            optional: true
          name: sysdig-agent-config
        - name: sysdig-agent-secrets
          secret:
            defaultMode: 420
            secretName: sysdig-agent
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
parameters:
- description: Region to target for sysdig agents
  displayName: Deployment Region
  name: REGION
  value: "app"
- description: Pod CPU Limit
  displayName: CPU Limit
  name: LIMIT_CPU
  value: "2"
- description: Pod Memory Limit
  displayName: Memory Limit
  name: LIMIT_MEM
  value: "1Gi"
- description: Pod CPU Request
  displayName: CPU Request
  name: REQUEST_CPU
  value: "150m"
- description: Pod Memory Request
  displayName: Memory Request
  name: REQUEST_MEM
  value: "256Mi"
