---
# tasks file for monitoring

# Lookup Team
- debug: msg=" Looking up {{ team.name }}"
- set_fact: 
    team_data: "{{ item }}"
    team_exists: true
  when: item.name == team.name
  with_items: 
    -  "{{ teams_output.json.teams }}"

- name: Test if team exists
  debug: msg="Team exists"
  when: team_exists == true

- name: show output
  debug: msg="{{ team_data }}"
  when: team_exists == true

- name: template test
  template: 
    src: templates/new_team.json.j2
    dest: test_output.json

# Create Team if Doesn't Exist
- name: Create Team
  block: 
  - name: Create team
    uri: 
      url: "{{ sysdig_api_endpoint }}/api/teams"
      method: POST
      headers:
          Authorization: "Bearer {{ sysdig_token }}"
          Content-Type: "application/json"
      body: "{{ lookup('template', 'templates/new_team.json.j2') }}"
      body_format: json
      status_code: 201
    register: team_creation_output
  when: team_exists == false
- debug: msg="{{ team_exists }}"


# Update Team if Exists Updates
- name: Update Team
  block: 
  - name: Update Team
    uri: 
      url: "{{ sysdig_api_endpoint }}/api/teams/{{ team_data.id | int }}"
      method: PUT
      headers:
          Authorization: "Bearer {{ sysdig_token }}"
          Content-Type: "application/json"
      body: "{{ lookup('template', 'templates/existing_team.json.j2') }}"
      body_format: json
      status_code: 200
    register: team_update_output
  when: team_exists == true
