---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    aqua_admin_password: "{{ lookup('env', 'AQUA_ADMIN_PASSWORD') }}"
    aqua_sso_client_secret: "{{ lookup('env', 'AQUA_SSO_LAB_CLIENT_SECRET') if 'lab' in lookup('env', 'AQUA_SSO_CLIENT') else lookup('env', 'AQUA_SSO_PROD_CLIENT_SECRET')}}"
  # Use a local vars file when testing locally; remotely the vars are passed from the webhook.
  # vars_files:
  #   creds/vars.yml
  tasks: 
    - include_tasks: tasks/login.yaml
    - include_tasks: tasks/enable_oidc.yaml