# permissions for end users to edit networksecuritypolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networksecuritypolicy-editor-role
rules:
- apiGroups:
  - security.developer.gov.bc.ca
  resources:
  - networksecuritypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.developer.gov.bc.ca
  resources:
  - networksecuritypolicies/status
  verbs:
  - get
