---
# defaults file for artifactory
console: ""
team_name: ""
repository_type: ""
repository_locator: ""
repository_description: ""
user: admin
artifactory_url: http://artifactory.devops-artifactory.svc.cluster.local:8081 
artifactory_repo_endpoint: artifactory/api/repositories
artifactory_permission_endpoint: artifactory/api/v2/security/permissions
artifactory_group_endpoint: artifactory/api/security/groups
artifactory_user_endpoint: artifactory/api/security/users
artifactory_token_endpoint: artifactory/api/security/token
list_virtual_repositories: ""
