- hosts: localhost
  gather_facts: no
  vars:
    k8s_message_key: _secops_pathfinder_gov_bc_ca_aporetoconsoleaccess
  tasks:
    - import_role:
        name: "aporetoconsoleaccess"
    - name: Extract variables
      set_fact:
        metadata: "{{ hostvars[inventory_hostname][k8s_message_key].metadata }}"
        spec: "{{ hostvars[inventory_hostname][k8s_message_key].spec }}"
