- hosts: localhost
  gather_facts: no
  tasks:
    - import_role:
        name: "networksecuritypolicy"
    - name: Debug Information 
      debug: 
        msg: "myvars = {{ hostvars[inventory_hostname] }}"
    - name: Extract k8s UID
      set_fact:
        k8s_uuid: "{{ hostvars[inventory_hostname]._secops_pathfinder_gov_bc_ca_networksecuritypolicy.metadata.uid }}"
    - name: Debug - Policy ID 
      debug: 
        msg: "Extracted UID = {{ k8s_uuid }}"
    - name: Policy Lookup
      when: k8s_uuid != ""
      shell: |
        /usr/local/bin/apoctl \
        api list networkaccesspolicies \
        -n /bcgov-devex/lab \
        --filter "associatedTags contains k8s-uuid={{ k8s_uuid }}" \
        -c ID
      register: output
    - name: Extract Policy ID
      when: output.stdout | from_json | list | length > 0
      set_fact:
        policy_id: "{{ (output.stdout | from_json | list | first).ID }}"
    - name: Debug - Policy Lookup
      debug:
        msg: "Extracted Policy ID = {{ policy_id }}"
    - name: Delete Policy
      when: policy_id != ""
      shell: |
        /usr/local/bin/apoctl \
        api delete networkaccesspolicies \
        -n /bcgov-devex/lab \
        "{{ policy_id }}"
    - name: Finished
      debug:
        msg: "Removed Policy {{ policy_id }} for k8s object {{ k8s_uuid }}"
