- hosts: localhost
  gather_facts: no
  vars:
    k8s_message_key: _secops_pathfinder_gov_bc_ca_networksecuritypolicy
    namespace: /bcgov-devex/lab
  tasks:
    - import_role:
        name: "networksecuritypolicy"
    - name: Debug Information 
      debug: 
        msg: "myvars = {{ hostvars[inventory_hostname] }}"
    - name: Extract k8s UID
      set_fact:
        metadata: "{{ hostvars[inventory_hostname][k8s_message_key].metadata }}"
    # Lookup the policy and fetch its uid; if a policy is found
    # `policy_id` will be defined.
    - import_tasks: lookup_netpol.yaml
      vars:
        k8s_uuid: "{{  metadata.uid  }}"
        appo_namespace: "{{ namespace }}"
    - name: Exist if no policy exists
      when: policy_id is not defined
      meta: end_play
    - name: Delete Policy
      when: policy_id is defined
      shell: |
        /usr/local/bin/apoctl \
        api delete networkaccesspolicies \
        --namespace "{{ namespace }}" \
        "{{ policy_id }}"
    - name: Finished
      debug:
        msg: "Removed policy {{ policy_id }} for k8s object {{ metadata.uid }}"
