- hosts: localhost
  gather_facts: no
  vars:
    k8s_message_key: _secops_pathfinder_gov_bc_ca_externalnetwork
  tasks:
    - import_role:
        name: "externalnetwork"
    - name: Extract variables
      set_fact:
        metadata: "{{ hostvars[inventory_hostname][k8s_message_key].metadata }}"
        spec: "{{ hostvars[inventory_hostname][k8s_message_key].spec }}"
    # Check if a the external network already exists. If so, return the `policy_id`
    # and `import_label` so they can be re-used as needed.
    - import_tasks: apo_lookup.yaml
      vars:
        k8s_uuid: "{{ metadata.uid  }}"
        apo_kind: externalnetworks
        apo_namespace: "{{ lookup('env', 'APOCTL_BASE_NAMESPACE') }}/{{ metadata.namespace }}"
    # Create or update a policy if it does not already
    # exists.
    - import_tasks: apo_import.yaml
      vars:
        k8s_uuid: "{{ metadata.uid }}"
        template_name: custom-extnet.yaml.j2
        apo_namespace: "{{ lookup('env', 'APOCTL_BASE_NAMESPACE') }}/{{ metadata.namespace }}"
        spec: "{{ spec }}"
    - name: Finished
      meta: end_play
