- hosts: localhost
  gather_facts: no
  vars:
    k8s_message_key: _secops_pathfinder_gov_bc_ca_networksecuritypolicy
  tasks:
    - import_role:
        name: "networksecuritypolicy"
    # - name: Debug Information 
    #   debug: 
    #     msg: "myvars = {{ hostvars[inventory_hostname] }}"
    - name: Generate policy ID
      command: openssl rand -hex 6
      register: openssl_cmd
    - name: Extract variables
      set_fact:
        puid: "{{ openssl_cmd.stdout }}"
        metadata: "{{ hostvars[inventory_hostname][k8s_message_key].metadata }}"
        spec: "{{ hostvars[inventory_hostname][k8s_message_key].spec }}"
    # Check if a the policy already exists. If so, return the ID
    # so it can be re-used later in the playbook.
    - import_tasks: apo_lookup.yaml
      vars:
        k8s_uuid: "{{ metadata.uid  }}"
        apo_kind: networkaccesspolicies
        apo_namespace: "{{ lookup('env', 'APOCTL_BASE_NAMESPACE') }}/{{ metadata.namespace }}"
    # Create or update a policy if it does not already
    # exists.
    - import_tasks: apo_import.yaml
      vars:
        pol_uid: "{{ policy_uid | default(puid) }}"
        k8s_uuid: "{{ metadata.uid }}"
        apo_namespace: "{{ lookup('env', 'APOCTL_BASE_NAMESPACE') }}/{{ metadata.namespace }}"
        spec: "{{ spec }}"
        template_name: custom-netpol.yaml.j2
    - name: Finished
      meta: end_play
