apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: alpine
labels:
  template: alpine
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      shared: true
    name: alpine
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: alpine:3.10
      importPolicy: {}
      name: "3.10"
      referencePolicy:
        type: Local
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      shared: true
    name: documize-conversion
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: documize/conversion:2.7.0
      importPolicy: {}
      name: "2.7.0"
      referencePolicy:
        type: Local
