apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${NAME}-bc-template
labels:
  template: ${NAME}
objects:
# ImageStreams:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      shared: true
    name: alpine
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: alpine:3.10
      importPolicy: {}
      name: "3.10"
      referencePolicy:
        type: Local
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      shared: true
    name: ${NAME}
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: documize/conversion:${CONVERSION_VERSION}
      generation: 2
      importPolicy: {}
      name: ${VERSION}
      referencePolicy:
        type: Local
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: documize-conversion
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: -dev
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
- description: Image source
  displayName: CONVERSION VERSION
  name: CONVERSION_VERSION
  required: true
  value: 2.7.0
