# openshift.withProject(env.PROJECT_NAME)
apiVersion: v1
kind: BuildConfig
metadata:
  name: "rocketchat-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
            agent any
            stages {
                stage('Input') {
                    steps {
                        script {
                            def userInput = input(
                                id: 'userInput', message: 'Enter name of environment to deploy and prefix of your environment',
                                parameters: [
                                    choice(choices: ['dev', 'prod', 'test'], description: '', name: 'environ'),
                                    string(defaultValue: 'a5bcde', description: '', name: 'prefix', trim: false),
                                ])
                            project = userInput.prefix+"-"+userInput.environ
                            environment = userInput.environ
                            echo("Deploying to Rocket Chat to: ${project}")
                        }
                    }
                }
                stage('Checkout') {
                    steps {
                        git branch: 'rc-work', url: 'https://github.com/BCDevOps/platform-services'
                    }
                }
                stage('Clean') {
                    when {
                        
                    }
                    steps {
                        sh "oc process -f apps/rocketchat/template-mongodb.yaml --param-file=apps/rocketchat/${environment}.env --ignore-unknown-parameters=true | oc delete -n ${project} -f - || :"
                        sh "oc process -f apps/rocketchat/template-rocketchat.yaml --param-file=apps/rocketchat/${environment}.env --ignore-unknown-parameters=true | oc delete -n ${project} -f - || :"
                        sh "oc delete -n ${project} pvc -l name=mongodb"
                    }
                }
                stage('Deploy') {
                    steps {
                        sh "oc process -f apps/rocketchat/template-rocketchat.yaml --param-file=apps/rocketchat/${environment}.env --ignore-unknown-parameters=true | oc create -n ${project} -f -"
                        sh "oc process -f apps/rocketchat/template-mongodb.yaml --param-file=apps/rocketchat/${environment}.env --ignore-unknown-parameters=true | oc create -n ${project} -f -"
                    }    
                }
                stage('Config') {
                    steps {
                        script {
                            openshift.withProject(project) {
                                sh ```
                                cd apps/rocketchat
                                wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
                                mv jq-linux64 jq
                                chmod +x jq
                                ./channel-creator.sh https://$(oc get route rocketchat | grep gov.bc | awk '{printf $2}') admin $(oc get configmap rocketchat-config -o yaml | grep -i admin_pass | awk '{printf $2}')
                                ```
                            }
                         }
                    }
                }
            }
        }


# add about delete storage too?
# add step delete just rocketchat keep mongo?
# add update image version with new env file, ask for env file
# ask for user password for shell script step
# trigger when push