apiVersion: v1
kind: BuildConfig
metadata:
  name: "rocketchat-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
            agent any
        
            stages {
                stage('Delete') {
                    steps {
                        script {
                            openshift.withProject(dev)
                        openshift.selector("all", [ template : templateName ]).delete()
                        #https://kubernetes.io/docs/tasks/run-application/delete-stateful-set/
                        }
                    }
                }
                stage('Checkout') {
                    steps {
                        git url: https://github.com/BCDevOps/platform-services
                    }
                }
                stage('Deploy') {
                    steps {
                        script {
                            openshift.withProject(dev) {
                                openshift.process("template-rocketchat-mongodb.yaml | oc create -f -")
                            }
                        }
                    }
                }
                stage('Config') {
                    steps {
                        script {
                            sh channel-creator.sh admin-user-name admin-password
                    }
                }
            }
        }