apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketchat-config
data:
  #File Upload Settings
  OVERWRITE_SETTING_FileUpload_Enabled: "True"
  OVERWRITE_SETTING_FileUpload_Storage_Type: "FileSystem"
  OVERWRITE_SETTING_FileUpload_ProtectFiles: "False"
  OVERWRITE_SETTING_FileUpload_FileSystemPath: "/app/uploads"
  OVERWRITE_SETTING_FileUpload_MaxFileSize: "2000000"
  #General Settings
  OVERWRITE_SETTING_Site_Url: "https://chat-pilot.pathfinder.gov.bc.ca"
  OVERWRITE_SETTING_Site_Name: "chat-pilot.pathfinder.gov.bc.ca"
  #Retention Settings
  OVERWRITE_SETTING_RetentionPolicy_Enabled: "True"
  OVERWRITE_SETTING_RetentionPolicy_AppliesToChannels: "True"
  OVERWRITE_SETTING_RetentionPolicy_MaxAgeChannels: "365"
  OVERWRITE_SETTING_RetentionPolicy_AppliesToGroups: "True"
  OVERWRITE_SETTING_RetentionPolicy_MaxAge_Groups: "365"
  OVERWRITE_SETTING_RetentionPolicy_AppliesToDMs: "True"
  OVERWRITE_SETTING_RetentionPolicy_MaxAge_DMs: "365"
  OVERWRITE_SETTING_RetentionPolicy_FilesOnly: "True"
  #Account Settings
  OVERWRITE_SETTING_Accounts_TwoFactorAuthentication_Enabled: "False"
  OVERWRITE_SETTING_Accounts_RegistrationForm: "Disabled"
  OVERWRITE_SETTING_Accounts_AllowRealNameChange: "False"
  OVERWRITE_SETTING_Accounts_AllowPasswordChange: "False"
  OVERWRITE_SETTING_Accounts_ShowFormLogin: "False"
  #Custom OAuth
  OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak: "True"
  OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-url: "https://sso-dev.pathfinder.gov.bc.ca/auth"
  OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-token-path: "/realms/devhub/protocol/openid-connect/token"
  OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-token_sent_via: "Header"
  OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-identity_path: "/realms/devhub/protocol/openid-connect/userinfo"
  OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-authorize_path: "/realms/devhub/protocol/openid-connect/auth"
  OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-id: "rocket-chat-test"
  OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-secret: "63cb2a21-f115-4750-be21-aaa26bb95726"
  OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-button_label_text: "Login"

# Rooms
# DevOps Alerts
# Random - Default
# DevOps Questions Community
# CSI Lab
# DevOps Platform Team
# Kudos - Default
# DevOps Request

# Permissions 
# Users- Manage Own Integrations: Enabled