apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: rocketchat
labels:
  template: rocketchat-build-template
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations: {}
    creationTimestamp: null
    name: ${NAME}
    labels:
        name: "${NAME}"
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ${ROCKETCHAT_IMAGE}:${ROCKETCHAT_IMAGE_TAG}
      importPolicy: {}
      name: "${ROCKETCHAT_IMAGE_TAG}"
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: rocket.chat
- name: ROCKETCHAT_IMAGE
  description: Location of the RocketChat Image
  displayName: RocketChat Image
  value: registry.hub.docker.com/library/rocket.chat
  required: true
- name: ROCKETCHAT_IMAGE_TAG
  description: Name of the RocketChat tag that should be used
  displayName: RocketChat Tag
  value: "2.4.1"
  required: true
