apiVersion: v1
kind: Template
metadata:
  name: mongodb-backup-template
  annotations:
    description: 'Template for MongoDB container backup job'
    tags: 'database,backup,mongo'
parameters:
  - name: MONGODB_BACKUP_KEEP
    description: 'Number of backups to keep'
    value: '7'
  - name: MONGODB_BACKUP_SCHEDULE
    description: 'Cron-like schedule expression. Default: Every hour at :39'
    value: '1 0 * * *'
  - name: MONGODB_BACKUP_VOLUME_CLAIM
    description: 'Name of the volume claim to be used as storage'
    value: ''
  - name: MONGODB_ADMIN_PASSWORD
    description: 'MongoDB admin user''s password. Required.'
objects:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: mongodb-backup
    spec:
      schedule: ${MONGODB_BACKUP_SCHEDULE}
      concurrencyPolicy: Forbid
      jobTemplate:             
        spec:
          template:
            spec:
              volumes:
                - name: mongodb-backup
                  persistentVolumeClaim:
                    claimName: ${MONGODB_BACKUP_VOLUME_CLAIM}
              containers:
                - name: mongodb-backup
                  image: 'docker-registry.default.svc:5000/openshift/mongodb:latest'
                  command:
                    - 'bash'
                    - '-c'
                    - >-
                      ls -rdt /var/lib/mongodb-backup/dump-* |
                      head -n -$MONGODB_BACKUP_KEEP |
                      xargs rm -rf &&
                      DIR=/var/lib/mongodb-backup/dump-`date +%F-%T` &&
                      mongodump -j 1 -u admin -p $MONGODB_ADMIN_PASSWORD --host $MONGODB_SERVICE_HOST --port $MONGODB_SERVICE_PORT --authenticationDatabase=admin --gzip --out=$DIR &&
                      echo &&
                      echo "To restore, use:" &&
                      echo "~# mongorestore -u admin -p \$MONGODB_ADMIN_PASSWORD --authenticationDatabase admin --gzip $DIR/DB_TO_RESTORE -d DB_TO_RESTORE_INTO"
                  resources:
                  limits:
                    cpu: 250m
                    memory: 1Gi
                  requests:
                    cpu: 100m
                    memory: 512Mi
                  env:
                    - name: MONGODB_BACKUP_KEEP
                      value: ${MONGODB_BACKUP_KEEP}
                    - name: MONGODB_ADMIN_PASSWORD
                      value: ${MONGODB_ADMIN_PASSWORD}
                  volumeMounts:
                    - name: mongodb-backup
                      mountPath: /var/lib/mongodb-backup
              restartPolicy: Never
