apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: link-${SECRET_NAME}-template
objects:
- apiVersion: v1
  kind: ServiceAccount
  imagePullSecrets: 
  - name: ${SECRET_NAME}
  metadata:
    name: builder
    namespace: ${NAMESPACE}
- apiVersion: v1
  kind: ServiceAccount
  imagePullSecrets: 
  - name: ${SECRET_NAME}
  metadata:
    name: default
    namespace: ${NAMESPACE}
parameters:
- description: Namespace
  displayName: namespace
  name: NAMESPACE
  required: true
- description: Secret Name
  displayName: Secret Name
  name: SECRET_NAME
  required: true
