apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: rocketchat
labels:
  template: rocketchat-secret-prep
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: template.rocketchat-config-secret
  stringData:
    #Custom OAuth:
    OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak: "${ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK}"
    OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-url: "${ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_URL}"
    OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-token_path: "${ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_TOKEN_PATH}"
    OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-token_sent_via: "${ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_TOKEN_SENT_VIA}"
    OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-identity_token_sent_via: "${ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_IDENTITY_TOKEN_SENT_VIA}"
    OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-identity_path: "${ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_IDENTITY_PATH}"
    OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-authorize_path: "${ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_AUTHORIZE_PATH}" 
    OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-id: "${ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_ID}"
    OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-secret: "${ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_SECRET}"
    OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-login_style: "${ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_LOGIN_STYLE}"
    OVERWRITE_SETTING_Accounts_OAuth_Custom-Keycloak-button_label_text: "${ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_BUTTON_LABEL_TEXT}"
    # bcgov SMTP server:
    OVERWRITE_SETTING_SMTP_Protocol: "${SMTP_PROTOCOL}"
    OVERWRITE_SETTING_SMTP_Host: "${SMTP_HOST}"
    OVERWRITE_SETTING_SMTP_Port: "${SMTP_PORT}"
    OVERWRITE_SETTING_SMTP_IgnoreTLS: "${SMTP_IGNORETLS}"
    OVERWRITE_SETTING_SMTP_Pool: "${SMTP_POOL}"
    OVERWRITE_SETTING_From_Email: "${FROM_EMAIL}"

parameters:
  - name: ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK
  - name: ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_URL
  - name: ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_TOKEN_PATH
  - name: ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_TOKEN_SENT_VIA
  - name: ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_IDENTITY_TOKEN_SENT_VIA
  - name: ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_IDENTITY_PATH
  - name: ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_AUTHORIZE_PATH
  - name: ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_ID
  - name: ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_SECRET
  - name: ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_LOGIN_STYLE
  - name: ACCOUNTS_OAUTH_CUSTOM_KEYCLOAK_BUTTON_LABEL_TEXT
  - name: SMTP_PROTOCOL
  - name: SMTP_HOST
  - name: SMTP_PORT
  - name: SMTP_IGNORETLS
  - name: SMTP_POOL
  - name: FROM_EMAIL
