apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: rocketchat-dockerhub-account-template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: dockerhub-account-rocketchat
    namespace: ${NAMESPACE}
  type: kubernetes.io/dockerconfigjson
  stringData:
    .dockerconfigjson: >-
      {"auths":{"${DOCKER_SERVER}":{"username":"${DOCKER_USERNAME}","password":"${DOCKER_PW}","email":"unused","auth":"dGVzdDp0ZXN0Mg=="}}}
- apiVersion: v1
  kind: ServiceAccount
  imagePullSecrets: 
  - name: dockerhub-account-rocketchat
  metadata:
    name: builder
    namespace: ${NAMESPACE}
- apiVersion: v1
  kind: ServiceAccount
  imagePullSecrets: 
  - name: dockerhub-account-rocketchat
  metadata:
    name: default
    namespace: ${NAMESPACE}
parameters:
- description: Namespace
  displayName: namespace
  name: NAMESPACE
  required: true
- description: Docker Username
  displayName: Docker Username
  name: DOCKER_USERNAME
  required: true
- description: Docker Password
  displayName: Docker Password
  name: DOCKER_PW
  required: true
- description: Docker Server
  displayName: Docker Server
  name: DOCKER_SERVER
  required: true