---
# tasks file for ExternalNetwork Create / Update
- name: Debug metadata
  debug:
    var: ansible_operator_meta
    verbosity: 3

- name: Debug description
  debug:
    var: description
    verbosity: 3

- name: Debug entires
  debug: 
    var: entries
    verbosity: 3

- name: Debug ports
  debug:
    var: servicePorts
    verbosity: 3

- name: Debug ExternalNetwork Import Vars
  debug:
    msg:
      - "aporeto_base_namespace: {{ aporeto_base_namespace }}"
      - "aporeto_namespace: {{ aporeto_namespace }}"
      - "import_label: {{ import_label }}"
      - "network_name: {{ network_name }}"
    verbosity: 1

- name: Create Or Update ExternalNetwork
  command: |
    apoctl api import \
    --namespace {{ aporeto_namespace }} \
    -f -
  args:
    stdin: "{{ lookup('template', 'custom-extnet.yaml.j2') }}"
