---
- name: Set aporeto_namespace
  set_fact:
    aporeto_namespace: "{{ aporeto_base_namespace }}/{{ ansible_operator_meta.namespace }}"

- include_tasks: import.yml
  when: state == 'present'

- include_tasks: delete.yml
  when: state == 'absent'
