#!/usr/bin/env groovy

//ENV Vars
def TOOLS_NAMESPACE = 'c81e6h-tools'
def DEV_NAMESPACE = 'c81e6h-dev'
def TEST_NAMESPACE = 'c81e6h-test'
def PROD_NAMESPACE = 'c81e6h-prod'
def PROMETHEUS_VERSION = 'latest'
def BLACKBOX_VERSION = 'latest'
def GRAFANA_VERSION = 'latest'
def ENVOY_VERSION = 'latest'
def GIT_REPO = 'BCDevOps/platform-services'
def BRANCH_NAME = 'status-page'


// Pipeline Execution

    node {
            stage ('Deploy Dev'){
                parallel (
                    'Prometheus': {
                        stage ('Stage1') {
                            git branch: "${BRANCH_NAME}", url: "https://github.com/${GIT_REPO}"
                            sh "ls -lha"
                            dir ("apps/statuspage/manifests") {
                                sh "ls -lha"
                                sh """oc apply -f service-prometheus.yml -n ${DEV_NAMESPACE}"""
                                sh """oc apply -f configmap-prometheus.yml -n ${DEV_NAMESPACE}"""
                                sh """oc apply -f route-prometheus.yml -n ${DEV_NAMESPACE}"""
                                sh """cat statefulset-prometheus.yml | sed 's/{{ VERSION }}/${PROMETHEUS_VERSION}/g'| oc apply -f - -n ${DEV_NAMESPACE}"""
                            }
                        }
                    },
                    'Blackbox': {
                        stage('Deploy Blackbox'){
                                sh """oc apply -f service-blackbox-exporter.yml -n ${DEV_NAMESPACE}"""
                                sh """oc apply -f configmap-blackbox-exporter.yml -n ${DEV_NAMESPACE}"""
                                sh """cat deployment-blackbox-exporter.yml | sed 's/{{ VERSION }}/${BLACKBOX_VERSION}/g'| oc apply -f - -n ${DEV_NAMESPACE}"""
                        }
                    },
                    'Grafana': {
                        stage('Deploy Grafana'){
                                sh """oc apply -f service-grafana.yml -n ${DEV_NAMESPACE}"""
                                sh """oc apply -f route-grafana.yml -n ${DEV_NAMESPACE}"""
                                sh """oc apply -f pvc-grafana.yml -n ${DEV_NAMESPACE}"""
                                sh """cat deployment-envoy.yml | sed 's/{{ VERSION }}/${GRAFANA_VERSION}/g'| oc apply -f - -n ${DEV_NAMESPACE}"""
                        }
                    },
                    'Envoy': {
                        stage('Deploy Envoy'){
                                sh """oc apply -f service-envoy.yml -n ${DEV_NAMESPACE}"""
                                sh """oc apply -f route-envoy.yml -n ${DEV_NAMESPACE}"""
                                sh """oc apply -f configmap-envoy.yml -n ${DEV_NAMESPACE}"""
                                sh """cat deployment-envoy.yml | sed 's/{{ VERSION }}/${ENVOY_VERSION}/g'| oc apply -f - -n ${DEV_NAMESPACE}"""
                        }
                    },
                )
                
            }
            stage ("Wait for Validation"){
                    input id: 'Approve02', message: 'Deploy in Test?', ok: 'HANG TIGHT!'
            }
            stage('Depoly in Test'){
                    sh "echo test"
            }
            stage('Testing Stage'){
                
                parallel (
                    'validate all upstreams': {
                        sh "echo load test"
                    },
                    'validate all components': {
                        echo "e2e test"
                    }
                )

            }
            stage ("Wait for Validation"){
                    input id: 'Approve03', message: 'Deploy in Prod?', ok: 'HANG TIGHT!'
            }
            stage ("Deploy in Production"){
                parallel (
                    'Prod Rollout': {

                    },
                    'Notify RocketChat': {
                        echo "Security Update"
                    }
                )
            }
    }
