apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: ExternalNetworkPolicy
metadata:
  name: custom-extnet
spec:
  name: secret-zone-x
  description: |
    specify a custom external network that can be
    referenced by name.
  entries:
  - 0.0.0.0/0
  protocols:
  - tcp
  ports:
  - "80"
  - "443"
