# permissions for end users to view sysdig-teams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sysdig-team-viewer-role
rules:
- apiGroups:
  - ops.gov.bc.ca
  resources:
  - sysdig-teams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.gov.bc.ca
  resources:
  - sysdig-teams/status
  verbs:
  - get
