apiVersion: v1
data:
  hooks.yml: |-
    - id: deploy_statuspage
      execute-command: /opt/deploy_statuspage.sh
      command-working-directory: /opt
      response-message: I got the payload!
      pass-arguments-to-command:
      - source: payload
        name: pull_request.head.repo.html_url
      - source: payload
        name: pull_request.head.ref
      - source: payload
        name: number
      - source: payload
        name: pull_request.head.repo.owner.login
      - source: payload
        name: pull_request.url
      trigger-rule:
        and:
        - match:
            type: payload-hash-sha1
            secret: mysecret
            parameter:
              source: header
              name: X-Hub-Signature
    - id: update_notifications
      execute-command: /opt/update_notifications.sh
      command-working-directory: /opt
      response-message: I got the payload!
      pass-arguments-to-command:
      - source: payload
        name: repository.html_url
      - source: payload
        name: ref
      - source: payload
        name: number
      - source: payload
        name: head.repo.owner.login
      - source: payload
        name: url
      trigger-rule:
        and:
        - match:
            type: payload-hash-sha1
            secret: mysecret
            parameter:
              source: header
              name: X-Hub-Signature
kind: ConfigMap
metadata:
  name: webhook-ansible-hooks
