apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: repo-mapper
labels:
  template: repo-mapper
objects:
- apiVersion: v1
  data:
    SMTP_HOST: ${SMTP_HOST}
    SMTP_PORT: ${SMTP_PORT}
    FROM_EMAIL: ${FROM_EMAIL}
    TO_A: ${TO_A}
    TO_B: ${TO_B}
    TO_C: ${TO_C}
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: ${NAME}-email-conf
- apiVersion: v1
  data:
    Caddyfile: |
      :2015

      root * /var/www/html

      file_server

      encode gzip
      log stdout
      log stderr
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: caddy-${NAME}-static${SUFFIX}
    labels:
      app: ${NAME}-static${SUFFIX}
      deploymentconfig: ${NAME}-static${SUFFIX}
      app-name: ${NAME}-static${SUFFIX}
# - apiVersion: v1
#   kind: ImageStream
#   metadata:
#     creationTimestamp: null
#     name: ${NAME}-static
#     labels: 
#       app: ${NAME}-static${SUFFIX}
#   spec:
#     lookupPolicy:
#       local: false
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}-static${SUFFIX}
    labels: 
      app: ${NAME}-static${SUFFIX}
  spec:
    minReadySeconds: 20 # should be ready for atleast 20 seconds before the container is considered available. This will allow us
    # to catch any errors on deploy before they are available to the web
    replicas: 1
    selector:
      deploymentconfig: ${NAME}-static${SUFFIX}
    strategy:
      resources:
        requests:
          cpu: '150m'
          memory: '50Mi'
        limits:
          cpu: '250m'
          memory: '105Mi'
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}-static${SUFFIX}
          app: ${NAME}-static${SUFFIX}
      spec:
        serviceAccountName: ${SA_NAME}
        containers:
        - name: ${NAME}-ansible
          image: ${ANSIBLE_IS_NAME}:${VERSION}
          args:
            - /bin/sh
            - -c
            - ./entrypoint.sh
          env:
          - name: OUTPUT_PATH
            value: ${OUTPUT_PATH}
          - name: SERVICE_NAME
            value: ${NAME}-static${SUFFIX}
          - name: SERVICE_NAMESPACE
            value: ${NAMESPACE}
          - name: WAIT_TIME
            value: ${WAIT_TIME}
          - name: SMTP_HOST
            valueFrom:
              configMapKeyRef:
                key: SMTP_HOST
                name: ${NAME}-email-conf
          - name: SMTP_PORT
            valueFrom:
              configMapKeyRef:
                key: SMTP_PORT
                name: ${NAME}-email-conf
          - name: FROM_EMAIL
            valueFrom:
              configMapKeyRef:
                key: FROM_EMAIL
                name: ${NAME}-email-conf
          - name: TO_A
            valueFrom:
              configMapKeyRef:
                key: TO_A
                name: ${NAME}-email-conf
          - name: TO_B
            valueFrom:
              configMapKeyRef:
                key: TO_B
                name: ${NAME}-email-conf
          - name: TO_C
            valueFrom:
              configMapKeyRef:
                key: TO_C
                name: ${NAME}-email-conf
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: ${OUTPUT_PATH}
            name: output-dir
        - name: ${NAME}
          image: ${NAME}-static:${VERSION}
          args:
            - /tmp/scripts/run
          ports:
          - containerPort: 2015
            protocol: TCP
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
          env:
          volumeMounts:
          - name: caddy-${NAME}-static${SUFFIX}
            mountPath: /etc/Caddyfile
            readOnly: true
            subPath: Caddyfile
          - mountPath: ${OUTPUT_PATH}
            name: output-dir
        volumes:
        - name: caddy-${NAME}-static${SUFFIX}
          configMap:
            defaultMode: 420
            name: caddy-${NAME}-static${SUFFIX}
        - name: output-dir
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}-static:${VERSION}
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}-ansible
        from:
          kind: ImageStreamTag
          name: ${ANSIBLE_IS_NAME}:${VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}-static${SUFFIX}
    labels: 
      app: ${NAME}-static${SUFFIX}
  spec:
    ports:
    - name: web
      port: 2015
      protocol: TCP
      targetPort: 2015
    selector:
      deploymentconfig: ${NAME}-static${SUFFIX}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/disable_cookies: 'true'
    creationTimestamp: null
    name: ${NAME}-static${SUFFIX}
    labels: 
      app: ${NAME}-static${SUFFIX}
  spec:
    host:
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}-static${SUFFIX}
      weight: 100
    wildcardPolicy: None
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: repo-mapper
- description: A name used for routes/services and deployment configs
  displayName: Host
  name: HOST
  required: false
  value: ''
- description: A volumn used for the caddy from config map
  displayName: volumn name
  name: CADDY_VOLUME_NAME
  required: false
  value: web-caddy-config
- description: The CPU Request for the deployment config
  displayName: CPU Request 
  name: CPU_REQUEST
  required: false
  value: 10m
- description: The CPU Limit for the deployment config
  displayName: CPU Limit 
  name: CPU_LIMIT
  required: false
  value: 100m
- description: The Memory Request for the deployment config
  displayName: Memory Request 
  name: MEMORY_REQUEST
  required: false
  value: 50Mi
- description: The Memory Limit for the deployment config
  displayName: Memory Limit 
  name: MEMORY_LIMIT
  required: false
  value: 75Mi
- description: Namespace for deployment
  displayName: NAMESPACE
  name: NAMESPACE
  required: true
  value: devhub-tools
- name: ANSIBLE_IS_NAME
  displayName: Ansible Imagestream Name
  value: metadata-ansible
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0
- description: Cluster read service account name. Note that it only works in devhub-tools namespace.
  displayName: service account name
  name: SA_NAME
  required: true
  value: cluster-view-sa
- description: Namespace where the service account is
  displayName: SA_NAMESPACE
  name: SA_NAMESPACE
  required: true
  value: devhub-tools
- description: Path to keep the output file
  displayName: OUTPUT_PATH
  name: OUTPUT_PATH
  required: true
  value: /var/www/html/
- description: Service to issue idle command
  displayName: SERVICE_NAME
  name: SERVICE_NAME
  required: true
  value: repo-mapper
- description: Namespace of the service
  displayName: SERVICE_NAMESPACE
  name: SERVICE_NAMESPACE
  required: true
  value: devhub-tools
- description: Time in seconds before idling the service
  displayName: WAIT_TIME
  name: WAIT_TIME
  required: true
- description: BCGOV smtp service host
  displayName: SMTP_HOST
  name: SMTP_HOST
  required: true
- description: BCGOV smtp service port
  displayName: SMTP_PORT
  name: SMTP_PORT
  required: true
- description: Email sent from
  displayName: FROM_EMAIL
  name: FROM_EMAIL
  required: true
- description: Email send to A
  displayName: TO_A
  name: TO_A
  required: true
- description: Email send to B
  displayName: TO_B
  name: TO_B
  required: true
- description: Email send to C
  displayName: TO_C
  name: TO_C
  required: true
