- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    artifactory_url: "https://artifacts.developer.gov.bc.ca"
    artifactory_group_endpoint: artifactory/api/security/groups
    artifactory_permission_endpoint: artifactory/api/v2/security/permissions
    service_account: "PASTE SERVICE ACCOUNT NAME HERE"
    repo_name: "PASTE PRIVATE REPOSITORY NAME HERE"
    admin_token: "PASTE ADMIN ACCOUNT TOKEN HERE"
    privileges: ["read","write","annotate","delete"] #please see DevHub for details on these privileges: https://developer.gov.bc.ca/Using-Artifactory


- name: Create artifactory group
  uri:
    url: "{{ artifactory_url }}/{{ artifactory_group_endpoint }}/{{ service_account }}"
    method: PUT
    body_format: json
    headers:
      Authorization: "Bearer {{ admin_token }}"
      Content-type: "application/json"
    body: '{"name": "{{ service_account }}","description" : "group to grant {{ service_account }} access to {{ repo_name }}","autoJoin" : false,"adminPrivileges" : false}'
    force_basic_auth: yes
    status_code: 201

- name: Add permission for repository
  uri:
    url: "{{ artifactory_url }}/{{ artifactory_permission_endpoint }}/{{ service_account }}"
    method: PUT
    body_format: json
    headers:
      Content-type: "application/json"
    body: '{
              "name": "{{ service_account }}",
              "repo":{
                  "include-patterns": ["**"],
                  "exclude-patterns": [""],
                  "repositories": ["{{ repo_name }}"],
                  "actions": {
                      "groups": {
                          "{{ service_account }}" : {{ privileges }}
                      }
                  }
              }
          }'
    force_basic_auth: yes
