name: sysdig-teams-operator-build-lab
on:
  push:
    branches:
      - '**'
      - '!master'
    paths: 
    - 'monitoring/sysdig/operator/sysdig-monitor/**'
    - '.github/workflows/**'

env: 
  TAG: "${{ secrets.LAB_SYSDIG_OPERATOR_SA_TOKEN }}"

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Get the current branch name
      shell: bash
      run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      id: branchref
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    # - name: Get the version
    #   id: vars
    #   run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: cd monitoring/sysdig/operator/sysdig-monitor && docker build . --file Dockerfile --tag bcdevopscluster/sysdig-teams-operator:${{ env.TAG }}
    - name: Push the tagged Docker image
      run: docker push bcdevopscluster/sysdig-teams-operator:${{ env.TAG }}
    # - name: OpenShift Action
    #   uses: redhat-developer/openshift-actions@v1.1
    #   with:
    #     version: '3.11.235'
    #     openshift_server_url: ${{ secrets.LAB_SYSDIG_OPERATOR_OPENSHIFT_SERVER_URL }}
    #     parameters: '{"apitoken": "${{ secrets.LAB_SYSDIG_OPERATOR_SA_TOKEN }}"}'
    #     cmd: |
    #       'project ${{ secrets.LAB_SYSDIG_OPERATOR_PROJECT }}'
    #       'delete is,bc -l build=gh-actions'
    #       'new-build https://github.com/BCDevOps/platform-services#${{ steps.branchref.outputs.branch }} --context-dir=monitoring/sysdig/operator/sysdig-monitor --name sysdig-teams-operator -l build=gh-actions'
    #       'tag is sysdig-teams-operator sysdig-teams-operator:lab'