name: sysdig-teams-operator-build-lab
on:
  push:
    branches:
    - '*'
    - '!master'
    paths: 
    - 'monitoring/sysdig/operator/sysdig-monitor/**'
    - '.github/workflows/**'
 
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Get the current branch name
      shell: bash
      run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      id: branchref
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v1.1
      with:
        version: '3.11.235'
        openshift_server_url: ${{ secrets.LAB_SYSDIG_OPERATOR_OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.LAB_SYSDIG_OPERATOR_SA_TOKEN }}"}'
        cmd: |
          'project ${{ secrets.LAB_SYSDIG_OPERATOR_PROJECT }}'
          'delete all -l build=gh-actions'
          'new-build https://github.com/BCDevOps/platform-services#${{ steps.branchref.outputs.branch }} --context-dir=monitoring/sysdig/operator/sysdig-monitor --name sysdig-monitor-operator -l build=gh-actions'