name: sysdig-teams-operator-build
on:
  push:
    branches:
    - 'bug/sysdig-teams'
    # paths: 
    # - 'monitoring/sysdig/operator/**'
 
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v1.1
      with:
        version: 'latest'
        openshift_server_url: ${{ secrets.SYSDIG_OPERATOR_OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.SYSDIG_OPERATOR_SA_TOKEN }}"}'
        cmd: |
          'oc project ${{ secrets.SYSDIG_OPERATOR_PROJECT }}'
          'oc get pods'