{
 "title": "Platform Services",
 "time": { "from": "2019-05-28T13:13:23.316Z", "to": "2019-05-29T01:13:23.316Z" },
 "panels": [
  { "title": "Cluster Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kubernetes API",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://kubernetes.default.svc.cluster.local\",job=\"blackbox_no_tls_verify\"}\t"
    }
   ]
  },
  {
   "title": "OpenShift Cluster API",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://console.lab.pathfinder.gov.bc.ca\",job=\"blackbox_tls_verify\"}\t"
    }
   ]
  },
  {
   "title": "Metrics API",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://hawkular-metrics.lab.pathfinder.gov.bc.ca\",job=\"blackbox_tls_verify\"}\t"
    }
   ]
  },
  {
   "title": "Lab Content",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://labs-devops-platform-workshops.lab.pathfinder.gov.bc.ca\",job=\"blackbox_tls_verify\"}\t"
    }
   ]
  },
  { "title": "Upstream Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "GitHub Connectivity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://github.com/bcdevops/platform-services\",job=\"blackbox_tls_verify\"}\t"
    }
   ]
  },
  {
   "title": "Fail Test",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://failme.lab.pathfinder.gov.bc.ca\",job=\"blackbox_tls_verify\"}\t"
    }
   ]
  },
  {
   "title": "Red Hat Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://access.redhat.com/containers/\",job=\"blackbox_tls_verify\"}\t"
    }
   ]
  },
  {
   "title": "DNS Resolution Time(s)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(probe_dns_lookup_time_seconds)"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Notices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Notices",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "content": "\n# SAMPLE TEXT\n\nSample Notice Details\n\n\n",
   "targets": [
    {}
   ]
  }
 ]
}